### ISSUE TITLE
Not working for PHP

### ISSUE THREAD

**Issue by alexparker** [ckovey/sublime-whitespace-coloring#1]
Tried it on my PHP.tmLanguage to no avail.

Are you or anyone still using this successfully? just want to make sure it's just me likely doing something incorrectly.

**Comment by ckovey** [comment]
Interesting, I just tried it on a fresh ST3 install against `Ruby.tmLanguage` and `JavaScript.tmLanguage` and this method still worked.  So my match must be conflicting with something specifically in the PHP one...

**Comment by ckovey** [comment]
Welp.. I'm sorry but I'm stumped with this PHP.tmLanguage file.  I see PHP is based off of the HTML tmLanguage file, however the coloring works with the HTML file.  As soon as I remove the `<?php` from my test php file, the color highlighting works.

I'm guessing it has something to do with `punctuation.whitespace.embedded.` properties, but there is a lot going on with this file and I don't know what all PHP relies on.

**Comment by alexparker** [comment]
Good to know! Thanks for looking into that further! I will try getting it working on some other syntaxes. I can live without it on PHP :)  Thanks!

**Comment by alexparker** [comment]
And if I can figure out a way to make it work with PHP using the right higherarchy or sequence of regex, then I'll post back here
