### ISSUE TITLE
Coloring Tab Indentation

### ISSUE THREAD

**Issue by LeonardoGentile** [ckovey/sublime-whitespace-coloring#2]
Hello,
is this applicable also to the whitespaces introduced by tabs?
For example, as you can see in the screenshot the tabs change color depending on the foreground color  of each block of code.
With your solution would I have more control on the tab colors?

![image](https://cloud.githubusercontent.com/assets/412061/6705733/164260ea-cd58-11e4-81a1-d4a529eb548c.png)

**Comment by ckovey** [comment]
Hi, sorry for the delay, never got the notification I guess, just noticed this when someone else created an issue recently.  

Yes this will highlight tabs as well as spaces for ST2.  ST3 it appears they changed to something different with http://www.sublimetext.com/docs/3/syntax.html  I have moved on to JetBrains products and no longer use Sublime so thats as far as I could guess for ST3

Anywho sorry for the delay.. better late than never?
